// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxfjhstrgiahxcebqadb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Zmpoc3RyZ2lhaHhjZWJxYWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzEyMjIsImV4cCI6MjA3MDYwNzIyMn0.lB-3_SgIIP_pc5EnIr1rZ8mpqLl5tochJBT_zVxi8x8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});